### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ulf78** [thebino/rki_covid#14]
I get this error after upgrading to 0.2.1
Even before the upgrade I already got "sensor unavailable" error for my county

Logger: homeassistant.components.sensor
Source: custom_components/rki_covid/sensor.py:74
Integration: Sensor (documentation, issues)
First occurred: 9:05:03 AM (2 occurrences)
Last logged: 9:05:03 AM

Error while setting up rki_covid platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rki_covid/sensor.py", line 53, in async_setup_entry
    sensors = [
  File "/config/custom_components/rki_covid/sensor.py", line 54, in <listcomp>
    RKICovidNumbersSensor(coordinator, district, info_type) for info_type in SENSORS
  File "/config/custom_components/rki_covid/sensor.py", line 74, in __init__
    data = coordinator.data[district]
TypeError: 'NoneType' object is not subscriptable

**Comment by ulf78** [comment]
double entry with #13
