### ISSUE TITLE
No data since today

### ISSUE THREAD

**Issue by AlfaJackal** [thebino/rki_covid#26]
The plug-in worked pretty well until this morning. Any ideas what causes this issue?

```
2021-02-12 12:02:31 ERROR (MainThread) [custom_components.rki_covid.api] Request failed <ClientResponse(https://api.corona-zahlen.org/districts) [502 Bad Gateway]>
<CIMultiDictProxy('Server': 'nginx/1.19.3', 'Date': 'Fri, 12 Feb 2021 11:02:31 GMT', 'Content-Type': 'text/html', 'Content-Length': '157', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000')>
2021-02-12 12:02:31 ERROR (MainThread) [custom_components.rki_covid] Error fetching rki_covid data: Error communicating with API: <ClientResponse(https://api.corona-zahlen.org/districts) [502 Bad Gateway]>
<CIMultiDictProxy('Server': 'nginx/1.19.3', 'Date': 'Fri, 12 Feb 2021 11:02:31 GMT', 'Content-Type': 'text/html', 'Content-Length': '157', 'Connection': 'keep-alive', 'Strict-Transport-Security': 'max-age=31536000')>
2021-02-12 12:02:49 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up rki_covid platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/rki_covid/sensor.py", line 83, in async_setup_entry
sensors = [
File "/config/custom_components/rki_covid/sensor.py", line 84, in <listcomp>
RKICovidNumbersSensor(coordinator, district, info_type) for info_type in SENSORS
File "/config/custom_components/rki_covid/sensor.py", line 104, in __init__
data = coordinator.data[district]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by AlfaJackal** [comment]
Don't know what happened here but I fixed it by deleting and (re-)installing it from the integration menu. A simple "reinstall" via HACS did not work.

**Comment by AlfaJackal** [comment]
Looks like it was too early for celebrating: 
After a few hours, the sensor is again "unavailable". There is something wrong, this issue has to be reopened.

**Comment by thebino** [comment]
Sorry, the data source is still/again broken: https://github.com/marlon360/rki-covid-api/issues/92

**Comment by rolandsteinmeyer** [comment]
Please make BASE_API_URL configurable via HACS, so we can use self-hosted rki-covid-api docker container without modifying const.py

**Comment by thebino** [comment]
Version 0.4.1 supports custom base url via `configuration.yaml`

```yaml
sensor:
  - platform: rki_covid
    baseurl: 'https://api.corona-zahlen.org'
    districts:
     - name: 'SK Augsburg'
     - name: 'SK Berlin Mitte'
     - name: 'BL Bayern'
     - name: 'LK München'
```
