### ISSUE TITLE
Integration broke on restart

### ISSUE THREAD

**Issue by Se7enair** [thebino/rki_covid#28]
The integration is working fine, till a restart of HA. Then it gets problems with the api.

```
Logger: custom_components.rki_covid
Source: helpers/update_coordinator.py:173
Integration: RKI Covid numbers (documentation, issues)
First occurred: 06:40:41 (1 occurrences)
Last logged: 06:40:41

Error fetching rki_covid data: Error communicating with API:
```

```
Logger: homeassistant.components.sensor
Source: custom_components/rki_covid/sensor.py:112
Integration: Sensor (documentation, issues)
First occurred: 06:40:56 (2 occurrences)
Last logged: 06:40:56

Error while setting up rki_covid platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rki_covid/sensor.py", line 91, in async_setup_entry
    sensors = [
  File "/config/custom_components/rki_covid/sensor.py", line 92, in <listcomp>
    RKICovidNumbersSensor(coordinator, district, info_type) for info_type in SENSORS
  File "/config/custom_components/rki_covid/sensor.py", line 112, in __init__
    data = coordinator.data[district]
TypeError: 'NoneType' object is not subscriptable
```

These are the errors I got.

System is up to date
core-2021.3.3
supervisor-2021.03.4
Home Assistant OS 5.12
RKI Covid numbers 0.4.1

Installed via HACS, configured via Lovelace UI

**Comment by oechslein** [comment]
I do see the same issue.

**Comment by AgentP38** [comment]
Yes for me too

**Comment by oechslein** [comment]
I guess it is the same as https://github.com/thebino/rki_covid/issues/26 (and others) meaning that the server https://api.corona-zahlen.org is overloaded (again).

**Comment by Se7enair** [comment]
But why exactly on a restart?
I installed it and get the right values, then 5minutes later I do a restart and get the problem. I can repeat that during the whole day. So it doesnt seem that overload is the problem.

**Comment by thebino** [comment]
@Se7enair on a restart all data are getting updated. Since this issue is recurring so often, I thinking about looking for a different backend or requesting directly from rki. Hosting the backend myself wasn't an option yet.

**Comment by Se7enair** [comment]
OK they get updated, but I tried a few times and every try the same. Fresh adding is working, restart not. All within a few minutes.
Strange....

Maybe it is an option to check every hour for new values if the last check wasnt successful?

**Comment by thebino** [comment]
@Se7enair There is an timedelta after restart before the data get requested for the first time, maybe this time is too long:
https://github.com/thebino/rki_covid/blob/master/custom_components/rki_covid/sensor.py#L28

The timedelta for refresh retries is managed by the internal DataCoordinator:
https://github.com/thebino/rki_covid/blob/master/custom_components/rki_covid/__init__.py#L82

**Comment by Se7enair** [comment]
@thebino for now, I changed to a rest-sensor directly from rki.

https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0/data?orderBy=GEN&page=10

If you are familiar with rest, maybe you really could change to rki as a source. 

```
platform: rest
name: Inzidenz Unterallgaeu
resource: "https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?where=GEN%20%3D%20'Unterallgäu'&outFields=cases7_per_100k&returnGeometry=false&outSR=4326&f=json"
value_template: '{{ value_json.features[0].attributes.cases7_per_100k | round(1) }}'
scan_interval: 3600
```

**Comment by LuckyTriple7** [comment]
I have the same Issue.
The Original Home Assistant Coronavirus Integration too.
Im opened an Isse here: https://github.com/home-assistant/core/issues/47811

2021-03-12 16:44:21 WARNING (MainThread) [homeassistant.setup] Setup of rki_covid is taking over 10 seconds.
2021-03-12 16:44:23 ERROR (MainThread) [custom_components.rki_covid] Error fetching rki_covid data: Error communicating with API: 

2021-03-12 16:44:58 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up rki_covid platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/rki_covid/sensor.py", line 91, in async_setup_entry
    sensors = [
  File "/config/custom_components/rki_covid/sensor.py", line 92, in <listcomp>
    RKICovidNumbersSensor(coordinator, district, info_type) for info_type in SENSORS
  File "/config/custom_components/rki_covid/sensor.py", line 112, in __init__
    data = coordinator.data[district]
TypeError: 'NoneType' object is not subscriptable

2021-03-12 17:19:28 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 71, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 117, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 133, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 216, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/rki_covid/config_flow.py", line 37, in async_step_user
    for case in sorted(coordinator.data.values(), key=lambda case: case.county):
AttributeError: 'NoneType' object has no attribute 'values'

**Comment by Se7enair** [comment]
The rest sensor is working continously since I added them.

So this seems to be a stable resource.

**Comment by tenenteandrea** [comment]
I had the same problem but than I realized that I made a mistake.
In editing configuration.yaml I move the ski_covid section using copy and paste and than the integration didn't work any longer. I discovered that I had to rewrite the names of the districts which used the "Umlaut" manually because the copy and paste most probably used another ?code? 
Not sure if this helps

**Comment by Se7enair** [comment]
I configured it via UI, so this didnt cause my problems.
But the problem you described sounds like typical yaml-thing.

**Comment by b10126** [comment]
I also had the problem @Se7enair and the others described. I just changed to arcgis directly via Rest (thanks for the tip @Se7enair !) and this works perfect. As I like the simpliness of the addin, perhaps there is a chance to switch, @thebino ?

**Comment by Stephan1908** [comment]
Hi,
@Se7enair:
Can you please give me a tip on how you came up with the link for the rest sensor?

"resource:" https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?where=GEN%20%3D%20'Unterallgäu'&outFields=cases7_per_100k&furn4seometr6out& = 100k&retal3232 json ""

I come from the lk Bernkastel-Wittlich.

Thank you.
greetings

**Comment by Se7enair** [comment]
Just change "Unterallgau" inside the link to your region.

**Comment by Stephan1908** [comment]
@Se7enair 
Hi,
Thank you for the quick answer, it worked.
Do you also have a tip for a "Bundesland", e.g. B. Rhineland-Palatinate?
greetings

**Comment by Se7enair** [comment]
As far as I see, the source is offering data only for districts (Landkreise, Stadtkreise, usw). So no data for states (Bundesländer).

**Comment by thebino** [comment]
@Se7enair Thats wrong, this integration is also offering "Unterallgäu"

Also I started parsing the rki data myself. There will be an update soon.

@Stephan1908 you should find "LK Unterallgäu" see the screenshot.

<img width="408" alt="Screenshot 2021-04-05 at 15 44 34" src="https://user-images.githubusercontent.com/841681/113580409-f7c87d00-9625-11eb-86d1-e3492e988c22.png">

**Comment by Se7enair** [comment]
If thought he want it as a rest sensor as I did it. And there I didn't found and "Bundesland" only " Landkreis"

**Comment by AgentP38** [comment]
I created a link one the Webpage of RKI...

So you can implement this as a sensor...

- platform: rest
  name: Inzidenz Niedersachsen
  resource: "https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Coronaf%C3%A4lle_in_den_Bundesl%C3%A4ndern/FeatureServer/0/query?where=LAN_ew_GEN%20%3D%20'NIEDERSACHSEN'&outFields=LAN_ew_AGS,LAN_ew_GEN,cases7_bl_per_100k&outSR=4326&f=json"
  value_template: '{{ value_json.features[0].attributes.cases7_bl_per_100k | round(1) }}'

**Comment by mib1185** [comment]
> @Se7enair on a restart all data are getting updated. Since this issue is recurring so often, I thinking about looking for a different backend or requesting directly from rki. Hosting the backend myself wasn't an option yet.

I have created a PR to switch to direct use of RKI API -> #34

**Comment by thebino** [comment]
The newest release is using the rki data via arcgis directly and not using corona-zahlen.org as datasource anymore after repeatedly outage. 

Please update to the [latest version](https://github.com/thebino/rki_covid/releases).
