### ISSUE TITLE
sensor.bl_nordrhein_westfalen_newcases: Number of new cases is much bigger than sensor.deutschland_newcases

### ISSUE THREAD

**Issue by abcdegon** [thebino/rki_covid#55]
During the last three days I set up a dashboard that shows new Covid cases from LK / NRW / Germany.
Every day the number of new cases is much bigger than the number of new cases in Germany. Today The numbers are:
```
sensor.deutschland_newcases == 7.050
sensor.bl_nordrhein_westfalen_newcases == 31.161
```
I expect that the sensor.bl_nordrhein_westfalen_newcases <= sensor.deutschland_newcases.

I installed the rki_covid integration on Friday, August 20th 2021. 
**💻 Versions (please complete the following information):**

 - OS: core-2021.8.8
 - Supervisor: supervisor-2021.06.8
 - Browser: Google Chrome on macOS
 - 
**🗄 Logfiles (Configuration > Logs)**

> 🎓 Increase the log level for this custom integration by adding the following lines to the `configuration.yaml`
```
logs:
2021-08-22 03:51:14 ERROR (MainThread) [custom_components.rki_covid] Unexpected error fetching rki_covid data:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
return await self.update_method()
File "/config/custom_components/rki_covid/__init__.py", line 78, in async_get_districts
await parser.load_data()
File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 22, in load_data
await self._load_districts_recovered()
File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 37, in _load_districts_recovered
await self._extract_districts_recovered(data)
File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 70, in _extract_districts_recovered
assert len(data["features"]) > 0
AssertionError

2021-08-21 09:50:58 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration rki_covid which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

```

**Comment by thebino** [comment]
This issue could not be reproduced in the last weeks, but the log also showed an issue while parsing. This is already fixed in the latest version of the parser.
