### ISSUE TITLE
Integration broken since 2021.9.x

### ISSUE THREAD

**Issue by TheZoker** [thebino/rki_covid#57]
**🐛 Describe the bug**

I just updated to version 2021.9.x and noticed, that the RKI numbers are no longer displayed. When I checked the logs, I got the error below. I also tried to remove all config entries and re-add them, but I got this error:
![image](https://user-images.githubusercontent.com/1368405/132665553-5bdfa12b-2e6e-4266-8956-7b308769fe7f.png)

**💥 When did the bug occurred.***
- [ ] Installation / First-run
- [ ] Configuration
- [X] Other

**👣 To Reproduce**

1. Go to `Integration`
2. Click on `Add integration`
3. Add `RKI Covid numbers` integration

**🧐 Expected behavior**

**💻 Versions (please complete the following information):**

 - OS: core-2021.9.5
 - Supervisor: supervisor-2021.09.0
 - Browser: all

**🗄 Logfiles (Configuration > Logs)**

```
Unexpected error fetching rki_covid data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/rki_covid/__init__.py", line 78, in async_get_districts
    await parser.load_data()
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 22, in load_data
    await self._load_districts_recovered()
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 37, in _load_districts_recovered
    await self._extract_districts_recovered(data)
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 70, in _extract_districts_recovered
    assert len(data["features"]) > 0
AssertionError
```

Another error:
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 211, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 72, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 179, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/rki_covid/config_flow.py", line 40, in async_step_user
    for case in sorted(coordinator.data.values(), key=lambda case: case.name):
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by marrobHD** [comment]
Same here

**Comment by temesinko** [comment]
The error seems to come from the parser package:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/rki_covid/__init__.py", line 78, in async_get_districts
    await parser.load_data()
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 22, in load_data
    await self._load_districts_recovered()
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 37, in _load_districts_recovered
    await self._extract_districts_recovered(data)
  File "/usr/local/lib/python3.9/site-packages/rki_covid_parser/parser.py", line 70, in _extract_districts_recovered
    assert len(data["features"]) > 0
AssertionError
```

**Comment by Hakko31** [comment]
Reinstalling RKI solved the problem for me

**Comment by thebino** [comment]
The error indicates, that the data source was unavailable. Since the data source is outside of my scope, and the error hasn't reoccured I will close this issue.
