### ISSUE TITLE
Broken after update to 2021.11.0b1

### ISSUE THREAD

**Issue by TheZoker** [thebino/rki_covid#64]
**🐛 Describe the bug**

After updating to HA `2021.11.0b1` I get these errors and I'm not able to add a new integration entity:
![image](https://user-images.githubusercontent.com/1368405/139419152-9858026e-a9f2-4eae-9fea-80ff7a8641ef.png)

I also tried to reinstall the integration, but that did not help. 

**💥 When did the bug occurred.***
- [x] Installation / First-run
- [ ] Configuration
- [ ] Other

**👣 To Reproduce**

1. Update HA to `2021.11.0b1`
2. Install RKI Covid
3. Add new integration

**🧐 Expected behavior**

Work

**💻 Versions (please complete the following information):**

 - OS: 2021.11.0b1
 - Supervisor: supervisor-2021.10.8
 - Browser: edge

**🗄 Logfiles (Configuration > Logs)**

```
2021-10-29 12:22:21 ERROR (MainThread) [custom_components.rki_covid] Error fetching rki_covid data: Error reading data from rki-covid-parser timed-out: 
2021-10-29 12:22:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 224, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/rki_covid/config_flow.py", line 40, in async_step_user
    for case in sorted(coordinator.data.values(), key=lambda case: case.name):
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by thebino** [comment]
Can't be reproduced. Perhaps there was a server issue with the API.
