### ISSUE TITLE
RKI Integration cannot be installed

### ISSUE THREAD

**Issue by huettenwirt** [thebino/rki_covid#8]
Hi,

I'm trying to install the rki_covid integration, but the installation fails. The error log shows a missing Attribute:
AttributeError: 'NoneType' object has no attribute 'values'

Here's the complete error log:

`

Logger: aiohttp.server
Source: custom_components/rki_covid/config_flow.py:37
First occurred: 08:19:50 (7 occurrences)
Last logged: 08:28:15
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/rki_covid/config_flow.py", line 37, in async_step_user
    for case in sorted(coordinator.data.values(), key=lambda case: case.county):
AttributeError: 'NoneType' object has no attribute 'values'

`

Am I doing something wrong or is this a general issue?

Thanks for your support and best regards,
Huettenwirt

**Comment by otterz** [comment]
I had the same issue. I think the reason of this issue is an invalid certificate for https://rki.marlon-lueckert.de/, the api that is been consumed by this integration.
Switching to http fixed the installation issue for me a few weeks ago. But now there seems to be an automatic rewrite to https on the server.

**Comment by mi4mac** [comment]
I do have the same issue since I am using version 2021.1.1.

**Comment by huettenwirt** [comment]
It seems the invalid certificate was fixed by Marlon. I deinstalled and re-installed the rki_covid integration and it works! Thanks for pointing to the base URL problem!
